name: Publish Auth API non GMS Implementation

on:
  workflow_run:
    # We'll run this workflow when the Publish Auth API is completed
    workflows: [ Publish Auth API ]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish Auth API non GMS implementation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Update local properties for secrets
        run: echo CLIENT_ID="CLIENT_ID_VALUE" > ./local.properties

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew :auth-api-non-gms:assembleRelease
      - name: Source jar
        run: ./gradlew androidSourcesJar

      # Runs upload to the staging repository
      - name: Publish to Staging area
        run: ./gradlew :auth-api-non-gms:publishReleasePublicationToSonatypeRepository --max-workers 1
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
